# spell-checker: disable
---
run:
  allow-parallel-runners: false
  concurrency: 6
  modules-download-mode: readonly
  tests: true
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errorlint
    - errname
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - ireturn
    - loggercheck
    # The tests have a high cyclometric complexity, disabling
    # - maintidx
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/memes
          - cloud.google.com
          - github.com/go-logr
          - github.com/google/uuid
          - github.com/mitchellh/go-homedir
          - github.com/spf13/cobra
          - github.com/spf13/viper
          - github.com/rs/zerolog
      test:
        files:
          - $test
        allow:
          - $gostd
          - github.com/memes
          - cloud.google.com
          - github.com/go-logr
          - github.com/google/uuid
  errcheck:
    check-type-assertions: true
    check-blank: true
  exhaustruct:
    exclude:
      - 'cloud\.google\.com/go/monitoring/apiv3/v2/monitoringpb\.CreateTimeSeriesRequest$'
      - 'cloud\.google\.com/go/monitoring/apiv3/v2/monitoringpb\.ListTimeSeriesRequest$'
      - 'github\.com/spf13/cobra\.Command$'
      - 'github\.com/memes/gce-metric/pkg/generators\.Metric$'
      - 'github\.com/memes/gce-metric/pkg/generators_test\.<anonymous>$'
      - 'github\.com/memes/gce-metric/pkg/pipeline_test\.<anonymous>$'
      - 'github\.com/rs/zerolog.ConsoleWriter$'
      - 'google\.golang\.org/genproto/googleapis/api/metric\.Metric$'
      - 'google\.golang\.org/protobuf/types/known/timestamppb\.Timestamp$'
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  nakedret:
    max-func-lines: 1
  nolintlint:
    allow-unused: false
    allow-no-explanation: []
    require-explanation: true
    require-specific: true
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
        xml: camel
        bson: camel
        avro: camel
        mapstructure: kebab
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
  uniq-by-line: false
output:
  formats:
    - format: tab
  print-issued-lines: false
  print-linter-name: true
  path-prefix: ""
  sort-results: true
