# Build gce-metric
# spell-checker: disable
---
project_name: gce-metric
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}-{{ .Commit }}
    goos:
      - freebsd
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    main: ./cmd/gce-metric/
    mod_timestamp: '{{ .CommitTimestamp }}'
gomod:
  proxy: true
archives:
  - format: binary
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    rlcp: true
source:
  enabled: true
  rlcp: true
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
sboms:
  - id: archive
    artifacts: archive
  - id: source
    artifacts: source
signs:
  - artifacts: checksum
    cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - --output-certificate
      - '${certificate}'
      - --output-signature
      - '${signature}'
      - '${artifact}'
    output: true
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  skip: true
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - memes/{{ .ProjectName }}:latest
      - memes/{{ .ProjectName }}:{{ .Tag }}
      - memes/{{ .ProjectName }}:{{ .Major }}
      - ghcr.io/memes/{{ .ProjectName }}:latest
      - ghcr.io/memes/{{ .ProjectName }}:{{ .Tag }}
      - ghcr.io/memes/{{ .ProjectName }}:{{ .Major }}
    dockerfile: Dockerfile
    use: docker
    build_flag_templates:
      # yamllint disable rule:line-length
      # spell-checker: enable
      - "--pull"
      - "--label=maintainer=Matthew Emes <memes@matthewemes.com>"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.authors=memes@matthewemes.com"
      - "--label=org.opencontainers.image.description=Generate a periodic set of metrics for autoscaling testing in GCP"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}/tree/{{ .FullCommit }}"
      - "--label=org.opencontainers.image.documentation={{ .GitURL }}/tree/{{ .FullCommit }}/README.md"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.url={{ .GitURL }}/tree/{{ .FullCommit }}/README.md"
      # spell-checker: disable
      # yamllint enable rule:line-length
docker_signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    artifacts: images
    output: true
    args:
      - sign
      - '${artifact}'
release:
  draft: false
  prerelease: auto
milestones:
  - close: true
    fail_on_error: false
    name_template: "{{ .Tag }}"
